site_metadata:
  title: "My Awesome Website"
  description: "Website created with fonte.wiki and Divisor"
  theme: "minima"
  github_repository_url: "git@github.com:fonte-wiki/Divisor.git"
  github_pages_url: "https://fonte-wiki.github.io/Divisor/"
  about_page_title: "About this site"
  about_page_body: "This is a sample description paragraph."

source_repository: "https://github.com/fonte-wiki/Backup-fonte-wiki"

content_mapping:
  home_page_source: "home.md"
  subpages_folder: "<none>"
  destination_folder: "site_contents"
  media_destination_folder: "assets/media"
